version: '3.8'
services:
  neo4j:
    image: neo4j:5.10
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    ports:
      - 7474:7474
      - 7687:7687
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

