services:
  neo4j:
    image: neo4j:5.15.0
    container_name: smart_rag_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"    # HTTP
      - "7687:7687"    # Bolt
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/neo4j123

      # APOC Plugin Configuration (behebt das APOC Problem)
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*

      # APOC Import/Export Configuration
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

      # Memory Settings für bessere Performance
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m

      # Additional Settings (ohne separate Config-Datei)
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474

      # Performance & Security Settings via ENV
      - NEO4J_dbms_connector_bolt_thread__pool__min__size=5
      - NEO4J_dbms_connector_bolt_thread__pool__max__size=400
      - NEO4J_dbms_transaction_timeout=60s
      - NEO4J_dbms_transaction_bookmark__ready__timeout=30s
      - NEO4J_dbms_security_auth__enabled=true

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      # Entferne neo4j.conf Volume - verwende nur ENV-Variablen

    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p neo4j123 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --- Qdrant Service hinzugefügt ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: smart_rag_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"    # Fixed host port mapping to ensure stable endpoint
    environment:
      # konservative defaults; Pfad wird durch Volume gemounted
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage
      - QDRANT__LOG__LEVEL=info
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:6333/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  qdrant_storage:
    driver: local

networks:
  default:
    name: smart_rag_network
